### ISSUE TITLE
Selected waypoint shows up when you switch worlds / dimensions

### ISSUE THREAD

**Issue by NyaomiDEV** [Sytm/waypoints2#90]
I was stress testing the dev build, when I found this obviously erratic behaviour.

So, if you remember my spawn waypoint...
![image](https://user-images.githubusercontent.com/13177694/222259067-08838473-614b-493a-9786-409c43c11cfc.png)

The particle trail still wants to lead me there, except it should not even show!

![image](https://user-images.githubusercontent.com/13177694/222258981-32d6a894-b44a-439a-a853-22e314e8a865.png)

**Comment by Sytm** [comment]
That shouldn't be happening...

Did you edit the config section regarding connected worlds? Otherwise I'll need to look into it

**Comment by NyaomiDEV** [comment]
```
  # Connected worlds in this list allow the translation of the coordinates 1:8, so you can for example navigate in the nether to a waypoint in the overworld
  connectedWorlds:
    - overworld: world
      nether: world_the_nether
```

But this is the End, lol?
